### ISSUE TITLE
docker环境登录图片验证码加载不出

### ISSUE THREAD

**Issue by Rebellioncry** [dromara/MaxKey#43]
验证码需要用到oraclejdk的相关代码，而构建docker引用的是openjdk，所以要么用oraclejdk的镜像，要么换一个captcha的开源工具，一般用docker的都喜欢用openjdk，所以有没有更好的解决方案？

**Comment by shimingxy** [comment]
报错如下：
`Caused by: java.lang.UnsatisfiedLinkError: /usr/local/openjdk-8/jre/lib/amd64/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory`

`Caused by: java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11FontManager`

解决方案请参考OpenJDK
https://www.xth8013.com/website/blogArticle/detail/55
https://www.it610.com/article/1297482295095140352.htm

**Comment by Rebellioncry** [comment]
@shimingxy 试了一下你提出的方案，发现实现并不方便。1、jib构建的命令属性里没有与RUN相对应的命令，导致没法在构建的时候就添加安装字库的代码，然后我是用docker stack命令运行容器的，compose文件会忽略build属性，导致没法从dockerfile再构建，本身这样也麻烦   2、我直接在运行后的容器内手动运行安装字库的命令，安装后也没有效果，可能只能在构建镜像之前就写好在dockerfile的run指令上，可是我们用的是jib，这样就又绕了一圈，不如直接打包jar自己构建镜像？
